# Generated by Django 6.0 on 2025-12-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('ANALISTA', 'Analista'), ('USUARIO', 'Usuario')], default='USUARIO', max_length=20),
        ),
    ]
