# Generated by Django 5.2.9 on 2025-12-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='probabilidad_abandono',
            field=models.FloatField(blank=True, help_text='Probabilidad (%) de que el cliente abandone', null=True),
        ),
    ]
